apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.masterName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.masterName }}
spec:
  replicas: {{ .Values.tooljet.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.masterName }}
  template:
    metadata:
      labels:
        app: {{ .Values.masterName }}
    spec:
      containers:
        - name: tooljet
          image: {{ .Values.tooljet.image }}:{{ .Values.tooljet.tag }}
          imagePullPolicy: IfNotPresent
          args: ["npm", "run", "start:prod"]
          ports:
            - containerPort: {{ .Values.env.PORT }}
          resources:
            requests:
              cpu: {{ .Values.tooljetResources.requests.cpu }}
              memory: {{ .Values.tooljetResources.requests.memory }}
            limits:
              cpu: {{ .Values.tooljetResources.limits.cpu }}
              memory: {{ .Values.tooljetResources.limits.memory }}
          envFrom:
            - secretRef:
                name: tooljet-secret