apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.masterName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}